### PR TITLE
Make sure no filters are null

### PR DESCRIPTION
**Pull request by Sohape**
I ran into an issue with a FilterProvider returning a null filter. Adding a defensive null-check fixed the problem

### CODE REVIEW

**Comment by scott-xu** [comment]
Hi @Sohape in which case the FilterProdiver returns null?

**Comment by Sohape** [comment]
I did not investigate further, as I had no more time. I have a fairly elaborate setup, so I will try to get some time to recreate it in a test project I can share with you

**Comment by Sohape** [comment]
So, I will try to explain the setup I have:

I am using Ninject in a ASP.NET WebApi 2 project. I have created a small library to help me test my APIs with an in-memory webserver. So in my unit test project I am using my library to run the API, and sometimes I want to mock some dependencies. Therefore I am using Ninject.MockingKernel & Ninject.MockingKernel.Moq. 

So, the FilterProvider that returns null is the NinjectFilterProvider. I am setting that up in my test, like this:

        private HttpConfiguration SetupHttpConfiguration(Action<HttpConfiguration> configInitFunc)
        {
            var config = new HttpConfiguration();
            configInitFunc(config);
            config.IncludeErrorDetailPolicy = IncludeErrorDetailPolicy.Always;
            config.Services.Replace(typeof(IFilterProvider), GetDefaultFilterProvider());
            config.Services.Replace(typeof(IHttpControllerActivator), new MoqControllerActivator(kernel));

            return config;
        }

        private IFilterProvider GetDefaultFilterProvider()
        {
            return new DefaultFilterProvider(kernel, new DefaultFilterProviders(GetFilterProviders()));
        }

        private IEnumerable<IFilterProvider> GetFilterProviders()
        {
            yield return new NinjectFilterProvider(kernel);
            yield return new ConfigurationFilterProvider();
            yield return new ActionDescriptorFilterProvider();
        }

The kernel here is a new MockingKernel instance. The configInitFunc is the normal WebApiConfig.Register. MoqControllerActivator is a simple IHttpControllerActivator implementation I made, but that is not relevant for this issue I think, so I will just leave it out for now.

The NinjectFilterProvider returns an IEnumerable<FilterInfo> where the first and only item is null. This is what is causing the problem as I then get a NullReferenceException in the DefaultFilterProvider.GetFilters method as shown in my pull request.

Unfortunately I do not have a lot of time, so the test project will have to wait. If you are not comfortable merging this pull request, then I am fine with that. I can create a wrapper around NinjectFilterProvider to filter any null values, and I can keep that in my library.

Maybe I should try to find time to write about my setup in a blog post or something :)

**Comment by Sohape** [comment]
I learned some more now. The reason NinjectFilterProvider returns en IEnumerable with a null value is because of the MockingKernel. The kernel.GetAll<INinjectFilter>(parameter) returns an Castle.Proxies.INinjectFilterProxy, and calling BuildFilter on that returns null.

I think I will just create a wrapper around NinjectFilterProvider, to get rid of that null value. I will close this pull request

**Pull request closed without merging**
